### PR TITLE
fix(scanner): spec-parsing + version-pin correctness in package-runner source resolution (MCP-2445)

### PR DESCRIPTION
**Pull request by Dumbris**
## Summary

Fixes a cluster of correctness bugs in scanner source resolution (Codex scanner audit, PRs #653–#670). The scanner mis-parsed several package-runner launch commands and ignored requested version pins, so it scanned the **wrong source** (or degraded to tool-definitions-only).

Refs against `origin/main`.

## Bugs fixed

- **Subcommand runners mis-parsed.** `pipx run X` → `"run"`, `pnpm dlx X` → `"dlx"` (returned the subcommand, not the package).
- **pnpm dead branch.** `resolveFromPackageFetch` dispatched pnpm but `isPackageRunnerCommand` excluded it → pnpm never reached the fetch.
- **Version pin ignored.** `resolveNpxCache` / `findUvxArchiveDir` / `findContainerTargetDir` picked newest-mtime, ignoring the requested version.
- **`--with` mis-handled.** `resolveUvxCache` only honored `--from`; `uvx --with <dep> <pkg>` resolved the extra dep, not the target.
- **No fetch timeout.** A hung/throttled registry could stall the scan indefinitely.
- **Unpinned cisco image.** `docker/scanners/cisco/Dockerfile` installed `cisco-ai-mcp-scanner` unpinned.

## Changes

- New command-aware `runnerPackageSpec()` parser: subcommand runners (`pipx run`, `pnpm dlx`, `yarn dlx`, `bun x`), package-naming flags (`npx --package/-p`, `uvx --from`), and skips non-target value flags (`uvx --with <dep>`, `-p/--python <ver>`, `-c <cmd>`). Replaces `firstPackageArg` and the ad-hoc parse loops in `resolveNpxCache` / `resolveUvxCache` / `npxTargetPackage` / `uvxTargetPackage` (host/container parity).
- `isPackageRunnerCommand` now includes `pnpm`/`yarn`/`bun`; npm fetch path dispatches them.
- Exact version pin honored in local caches (npx package.json version, uvx `.dist-info` version, container npx bucket), falling back to newest/first when unpinned or unmatched.
- 90s bounded timeout around the published-source fetch (download + extract).
- Pinned `cisco-ai-mcp-scanner==4.7.3` (reproducible, rug-pull guard).

## Tests (TDD)

- `TestRunnerPackageSpec` — table tests: `pipx run X`, `pnpm dlx X`, `yarn dlx X`, `bun x X`, `npx -p`, `uvx --from`, `uvx --with`, `uvx -p/--python` → `X`.
- `TestResolveNpxCacheHonorsPinnedVersion`, `TestResolveUvxCacheArchiveHonorsPinnedVersion` — pinned version selected over newer mismatch.
- `TestResolveUvxCacheWithFlag` — `--with <dep>` does not shadow the target.
- `TestNpxContainerLocateScript` — generated `/bin/sh` locate script run on the host: version pin selects the matching bucket; no pin returns first match.

```
go test ./internal/security/... -race   # green
golangci-lint run --config .github/.golangci.yml ./internal/security/scanner/   # 0 issues
```

Docs updated in the same PR (`docs/features/security-scanner-plugins.md`).

Related MCP-2445

### CODE REVIEW

**Comment by Dumbris** [comment]
### CI note — pre-existing `Server Edition` failure is NOT from this PR

The `Server Edition` check is red, but it is a **pre-existing build break on `origin/main`**, unrelated to this change:

```
internal/teams/broker/oauth_connector.go:95: undefined: CredentialStore
internal/teams/broker/oauth_connector.go:184: undefined: UpstreamCredential
internal/teams/broker/oauth_connector_test.go:46: undefined: openTestDB
...
FAIL github.com/smart-mcp-proxy/mcpproxy-go/internal/teams/broker [build failed]
```

`CredentialStore` / `UpstreamCredential` are referenced but **never defined** anywhere in `internal/teams/` — introduced by #602 (spec 074, per-user OAuth broker). This PR touches only `internal/security/scanner/`, `docs/`, and `docker/scanners/cisco/`, none of which are server-edition-tagged. `go build -tags server ./cmd/mcpproxy` and `go test -tags server ./internal/security/...` are green locally on this branch.

`Server Edition` is **not** a required status check, so it does not gate merge. Flagging it separately for a follow-up fix (out of scope for MCP-2445).

**Required checks status:** Lint ✓, Build (ubuntu-latest) ✓, Build Frontend ✓, Validate PR title ✓, Verify OpenAPI ✓, swift-test/settings-parity skipping. Unit Tests completing. The scanner docker images (cisco/ramparts/snyk) build green, incl. `cisco` on linux/amd64+arm64 (validates the version pin).

**Comment by Dumbris** [comment]
**codex review (gpt-5.5) → REQUEST_CHANGES** (independently re-verified)

Blocking bug: `runnerPackageSpec` does **not require** the subcommand keyword for subcommand-style runners. For `pnpm`/`yarn`/`pipx`/`bun`, when `dlx`/`run`/`x` is absent the first positional is returned anyway: `pnpm start` → package `"start"`, `bun server.ts` → `"server.ts"`. Combined with `isPackageRunnerCommand` now returning true for bare `pnpm`/`yarn`/`bun`, a normal non-runner launch is mis-classified and the scanner fetches/scans the **wrong published package** (false coverage + typosquat-fetch risk). Same flaw in the `resolveNpxCache` cache-resolve path.

Fix: only treat the first positional as a package spec when the runner **subcommand keyword is present** (`pipx run`/`pnpm dlx`/`yarn dlx`/`bun x`); `isPackageRunnerCommand` can't classify `pnpm`/`yarn`/`bun` by exe name alone. Add tests for `pnpm start`, `bun server.ts`.

**Comment by Dumbris** [comment]
**codex RE-REVIEW (gpt-5.5) → REQUEST_CHANGES** (round 2 — the `pnpm start`→`start` case is handled, but related holes remain)

1. **`-p`/`--package` flag bypass (concrete blocker):** `runnerPackageSpec` processes the package flag (`-p <pkg>`) **before** enforcing the `dlx`/`x` subcommand, so `pnpm -p start` / `bun -p server.ts` still produce a package spec without the required runner subcommand. Enforce the subcommand keyword **first**, then parse flags.
2. **Classification still by-name:** `isPackageRunnerCommand` classifies bare `pnpm`/`yarn`/`bun` by command name alone, so `pnpm start` / `bun server.ts` stay on package-runner paths and rely on later parser failure rather than correct classification. Make classification argument-aware (a runner only when its subcommand is present).
3. **Cache version-pin fallback:** when an exact pin is requested but not present in cache, it still falls back to a mismatched cached package — suppressing the published fetch of the requested version (false scanner coverage). Don't substitute a different version.

Add tests for `pnpm -p start`, `bun -p server.ts`, and the version-pin-miss case.

**Comment by Dumbris** [comment]
**codex RE-REVIEW (gpt-5.5) → REQUEST_CHANGES** (round 3 — the 3 prior blockers are now FIXED ✅: subcommand-keyword-first parsing, argument-aware classification, host-side npx/uvx pin-miss returns error). One **new in-scope** blocker:

**Container-side version match uses unescaped `grep -E`** — `npxContainerLocateScript` (source_resolver.go:806) greps the version as an ERE, so `.` is a wildcard. A pin like `pkg@1.0.0-alpha.1` matches cached `1.0.0-alpha-1`, substituting the WRONG cached package despite the host-side pin-miss guard. Since MCP-2445 covers npx/container version-pin correctness, this is in scope. Fix: use fixed-string comparison (`grep -F`) or JSON-parse + exact string equality for the container cache path. Add a test with a regex-special version (e.g. `1.0.0-alpha.1` vs `1.0.0-alpha-1`).
